### ISSUE TITLE
Make bindfs buildable as kernel module

### ISSUE THREAD

**Issue by Harvie** [mpartel/bindfs#33]
Ultimate goal would be to write bindfs in such manner that would enable it to be compiled as both, fuse binary and linux kernel module while using common code base...

Just idea :-) But it may improve performance...

If this will not be possible, then fork may be interresting.

**Comment by mpartel** [comment]
I don't realistically see myself doing this any time soon, but I'd be happy to review a PR for it if someone really wants this feature.

I'm not sure how feasible this is to do with a single codebase since the kernel's filesystem interfaces are probably significantly different from userspace. Do you know of any FUSE filesystem that takes this approach?

**Comment by hartwork** [comment]
The kernel and userspace do not even share the same `malloc`, my vote for closing this as unfeasible.

**Comment by mpartel** [comment]
Malloc and other missing functions are unlikely to be the biggest hurdle, but I agree that this can be closed since the effort required would be significant and the real-world benefits probably tiny.

Anyone with high performance requirements probably can and should avoid a layer like bindfs anyway, in-kernel or not.
