### ISSUE TITLE
Mirrors for source tarballs

### ISSUE THREAD

**Issue by gael-ian** [mpartel/bindfs#35]
Hi,

I know it's something really rare but today bindfs.org have been unavailable for a while. Meantime, someone try to build a new VM with Vagrant and the [vagrant-bindfs plugin](https://github.com/gael-ian/vagrant-bindfs). The plugin try to install bindfs from source (which happen only when no official package is available for the guest distro) and [fails, unable to download the source tarballs](https://github.com/gael-ian/vagrant-bindfs/issues/46).

Is there any official mirror for source releases ? or is it possible to build one ?  
I try to use github releases instead of bindfs.org ones but they are not build the same way and I don't want to add the additionnal dependencies of your makerelease.sh script to the plugin.

Thanks

**Comment by mpartel** [comment]
Really sorry about the downtime, I did a domain transfer carelessly and now
the wrong result appears to be cached all over the place for a really long
time.

I'll think about setting up a mirror but unfortunately can't do it right
now.
On 1 Jul 2016 3:55 pm, "Gaël-Ian" <notifications@github.com> wrote:

Hi,

I know it's something really rare but today bindfs.org have been
unavailable for a while. Meantime, someone try to build a new VM with
Vagrant and the vagrant-bindfs plugin
<https://github.com/gael-ian/vagrant-bindfs>. The plugin try to install
bindfs from source (which happen only when no official package is available
for the guest distro) and fails, unable to download the source tarballs
<https://github.com/gael-ian/vagrant-bindfs/issues/46>.

Is there any official mirror for source releases ? or is it possible to
build one ?

I try to use github releases instead of bindfs.org ones but they are not
build the same way and I don't want to add tha additionnal dependencies of
your makerelease.sh script to the plugin.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mpartel/bindfs/issues/35>, or mute the thread
<https://github.com/notifications/unsubscribe/AAUE-Ets7Mxh64yn0UzT3E62tQC-XnaCks5qRSpmgaJpZM4JDN4i>
.

**Comment by gael-ian** [comment]
No problem, there's no urgency. It was an open question.
Thanks for your answer.

**Comment by lchrusciel** [comment]
Same problem one more time. I don't want to hurry you, but I just want to say, it would be awesome to see `bindfs.org` working one more time. :)

**Comment by mpartel** [comment]
I set **http://bindfs.dnsalias.net/** to point to the site as a temporary fix. I'll probably keep it around for the foreseeable future, but if you set it in a script, I'd appreciate it if you could change it back once this mess has been fixed.

It's still in the same state: I can access it with two different mobile providers, but it's still inaccessible both at home and at work.

`dig bindfs.org` doesn't find it, but `dig +trace bindfs.org` does, and none of the TTLs it shows are over 48 hours. I'm no expert on DNS but this seems to go beyond any negative caching that should take place. Any ideas would be appreciated.

I'll contact Gandi support now.

**Comment by lchrusciel** [comment]
Thanks @mpartel

**Comment by mpartel** [comment]
Fixed now. Turns out a DNSSEC key had been set for some reason, and it was invalid, for some reason.

Sorry again for my poor response time.

As I said, I'll leave the alias up as a fallback. I might set up a proper mirror some day.

Amusingly, it turns out archive.org [kept a copy](https://web.archive.org/web/20160512000019/http://bindfs.org/downloads/) of even the tarballs.
