### ISSUE TITLE
Please drop default compile flags or add means to bypass then

### ISSUE THREAD

**Issue by hartwork** [mpartel/bindfs#42]
Hi!

I have just bumped bindfs to the latest release in Gentoo. While Gentoo may be special with regards to compile flags, packagers of other source-based distributions will probably want to get rid of the extension of `CFLAGS` that `configure.ac` does, too. Right now, that needs patching them out, e.g. this way https://github.com/gentoo/gentoo/commit/e75f94d0155e88f8bad4e1ea90c0723c6e5c5557#diff-85c906dae59cc718b8c17c461475dc88 . It would be cool if I could resolve that patch at some point in the future (and to not forward-port it on upstream changes to configure.ac). Could you add means to bypass that extension or to drop it altogether? That would be appreciated. Thank you!

Best, Sebastian

**Comment by mpartel** [comment]
Sorry, busy times. I'll take a better look in a week or so. In the meantime could you point to an example project that does this "correctly"? I'm inclined to leave -O2 as the default since I feel `./configure && make && make install` should always give reasonable defaults, but I'm also happy to add an option to leave `my_CFLAGS` empty.

**Comment by mpartel** [comment]
Applied your patch in 1.13.5, thanks

**Comment by hartwork** [comment]
Many thanks!

I think that leaves `AC_ARG_ENABLE([debug], ...)` as a no-op so maybe remove that as well. Again, many thanks!

**Comment by mpartel** [comment]
You're right, removed, thanks.
