### ISSUE TITLE
Volumes mounted with bindfs not visible in the 'Locations' of MacOS Sidebar

### ISSUE THREAD

**Issue by diyoyo** [mpartel/bindfs#67]
Volumes mounted with bindfs are not visible in the 'Locations' of MacOS Sidebar, unlike my external HDD, for instance.
Is there any ways to solve this?
Thanks.

**Comment by mpartel** [comment]
I think this is just how FUSE on OS X works by default: https://github.com/osxfuse/osxfuse/wiki/FAQ#4-other-usage-questions

It's worth reading that link, but TL;DR: you can try `-o local` (but it has some other implications too).

I'll close this because I don't think bindfs does anything special here. Please feel free to reopen if you disagree.
