### ISSUE TITLE
Obtaining Read/Write Metrics for Performance Testing

### ISSUE THREAD

**Issue by jdgiotta** [mpartel/bindfs#68]
My team is using bindfs as part of a larger project. We experience some performance issues, but we don't think it is bindfs, but some other component related to the project.

Is there a way to log operations from bindfs in order to observe read/write speeds?

**Comment by mpartel** [comment]
You can use `-f` to foreground bindfs and `-d` to print debug info (you get more if you build with `./configure --enable-debug`). It doesn't print any timings by default. You can edit `debug.h` if you'd like to change that, or you can try something like [`ts`](https://unix.stackexchange.com/questions/26728/prepending-a-timestamp-to-each-line-of-output-from-a-command). You could also try `ts strace -f bindfs [-f] ...` for even more detail.

Bindfs should also work with most profilers, but that doesn't necessarily tell the full story, since FUSE filesystems involve the kernel module as well. Due to those extra roundtrips, I'd expect bindfs to perform better with fewer large files than many small ones.

**Comment by jdgiotta** [comment]
Excellent, thank you!

**Comment by mpartel** [comment]
Sorry, small correction: it's `./configure --enable-debug-output`. But what that adds is probably not very useful in your case.

**Comment by jdgiotta** [comment]
Thanks again, Martin. I found the culprit.
