### ISSUE TITLE
deprecated warning from brew doctor

### ISSUE THREAD

**Issue by CaledoniaProject** [mpartel/bindfs#90]
brew doctor output the following information:

```
Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  bindfs
```

But bindfs is still under active development, so what was wrong about it?

**Comment by mpartel** [comment]
bindfs is still maintained, but I'm not the one that maintains the brew formula. The [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bindfs.rb) says `deprecate! because: "requires FUSE"`. The [reason](https://github.com/Homebrew/homebrew-core/pull/64491) seems to be that MacFUSE is no longer open source.

I don't think there's much I can do about that :neutral_face: 

You should still be able to build bindfs manually, though I haven't tested on Big Sur yet.

**Comment by CaledoniaProject** [comment]
I'll run some tests on Big Sur tonight.
